BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "dua_contents" (
	"id" INTEGER NOT NULL,
	"slug" TEXT NOT NULL UNIQUE,
	"sort_order" INTEGER NOT NULL,
	"content_html" TEXT NOT NULL,
	"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
